export const TRIGGER = 'TRIGGER';


export const CARD_SEARCH = 'CARD_SEARCH';
export const SEARCHED_CARDS_RECIEVED = 'SEARCHED_CARDS_RECIEVED';
export const SEARCHED_CARDS_FORMATTED = 'SEARCHED_CARDS_FORMATTED';