export const TRIGGER = 'TRIGGER';


export const CARD_SEARCH = 'CARD_SEARCH';
export const SEARCHED_CARDS_RECIEVED = 'SEARCHED_CARDS_RECIEVED';
export const SEARCHED_CARDS_FORMATTED = 'SEARCHED_CARDS_FORMATTED';
export const ADD_CARD_TO_COLLECTION = 'ADD_CARD_TO_COLLECTION';
export const ADD_CARD_TO_DECK = 'ADD_CARD_TO_DECK';
